### ISSUE TITLE
Typescript TS2305: Module 'createApplication' has no exported member 'CookieOptions'.

### ISSUE THREAD

**Issue by huineng** [slavomirvojacek/adbrain-typescript-definitions#4]
I have the following problem with express-session using express 4.14.0
and typings dt~express or npm~express

error =>  typings/globals/express-session/index.d.ts(43,24): error TS2305: Module 'createApplication' has no exported member 'CookieOptions'.

**Comment by slavomirvojacek** [comment]
Hi @huineng, I updated all the definitions just now, but you might want to take a look at https://github.com/DefinitelyTyped/DefinitelyTyped.

Hope this helps!
